from dataclasses import dataclass
from typing import List, Set, Optional


@dataclass(frozen=True)
class LanguageRule:
    name: str
    pattern: str
    severity: str
    category: str
    description: str
    extensions: Set[str]
    ignore_in_comments: bool = True
    ignore_in_strings: bool = False
    taint_source: Optional[str] = None
    taint_sink: Optional[str] = None


def _exts(*args) -> Set[str]:
    return set(args)


LANGUAGE_RULES: List[LanguageRule] = [
    # ══════════════════════════════════════════════════════════════
    # PYTHON RULES (use AST analyzer for high-confidence detection)
    # ══════════════════════════════════════════════════════════════
    LanguageRule("Python eval(input)", r'eval\s*\(\s*(?:input|raw_input)',
                "CRITICAL", "INJECTION", "eval() with user input - code injection.",
                _exts(".py"), taint_source="input", taint_sink="eval"),
    LanguageRule("Python exec(input)", r'exec\s*\(\s*(?:input|raw_input)',
                "CRITICAL", "INJECTION", "exec() with user input.",
                _exts(".py"), taint_source="input", taint_sink="exec"),
    LanguageRule("Python subprocess shell=True", r'subprocess\.\w+\s*\(.*shell\s*=\s*True',
                "HIGH", "INJECTION", "subprocess with shell=True.",
                _exts(".py"), taint_source="request", taint_sink="subprocess"),
    LanguageRule("Python os.system", r'os\.system\s*\(', "HIGH", "INJECTION",
                "os.system() allows command injection.",
                _exts(".py"), taint_sink="os.system"),
    LanguageRule("Python os.popen", r'os\.popen\s*\(', "HIGH", "INJECTION",
                "os.popen() allows command injection.",
                _exts(".py"), taint_sink="os.popen"),
    LanguageRule("Python pickle.load", r'pickle\.loads?\s*\(', "CRITICAL", "DESERIALIZATION",
                "Pickle deserialization allows RCE.",
                _exts(".py"), taint_sink="pickle.load"),
    LanguageRule("Python yaml.load", r'yaml\.load\s*\((?!.*Loader)',
                "HIGH", "DESERIALIZATION", "yaml.load without SafeLoader.",
                _exts(".py")),
    LanguageRule("Python marshal.load", r'marshal\.loads?\s*\(', "CRITICAL", "DESERIALIZATION",
                "Marshal deserialization allows RCE.",
                _exts(".py")),
    LanguageRule("Python flask render_template_string", r'render_template_string\s*\(',
                "CRITICAL", "INJECTION", "Jinja2 SSTI vulnerability.",
                _exts(".py"), taint_sink="render_template_string"),
    LanguageRule("Python flask send_file", r'send_file\s*\(\s*(?:request|req)',
                "HIGH", "TRAVERSAL", "Flask send_file with user input.",
                _exts(".py"), taint_source="request", taint_sink="send_file"),
    LanguageRule("Python hashlib.md5", r'hashlib\.md5\s*\(', "HIGH", "CRYPTO",
                "MD5 is cryptographically broken.",
                _exts(".py")),
    LanguageRule("Python hashlib.sha1", r'hashlib\.sha1\s*\(', "MEDIUM", "CRYPTO",
                "SHA1 is deprecated.",
                _exts(".py")),
    LanguageRule("Python hashlib.md5", r'hashlib\.md5\s*\(', "HIGH", "CRYPTO",
                "MD5 is cryptographically broken.",
                _exts(".py")),
    LanguageRule("Python tempfile.mktemp", r'tempfile\.mktemp\s*\(', "HIGH", "CONFIG",
                "mktemp() is insecure. Use mkstemp().",
                _exts(".py")),
    LanguageRule("Python django DEBUG", r'DEBUG\s*=\s*True', "HIGH", "CONFIG",
                "Django DEBUG mode enabled.",
                _exts(".py")),
    LanguageRule("Python flask debug", r'app\.run\s*\(.*debug\s*=\s*True',
                "MEDIUM", "CONFIG", "Flask debug mode enabled.",
                _exts(".py")),
    LanguageRule("Python chmod 777", r'os\.chmod\s*\(.*0o?777', "HIGH", "CONFIG",
                "World-writable permissions.",
                _exts(".py")),
    LanguageRule("Python requests verify=False", r'requests\.\w+\s*\(.*verify\s*=\s*False',
                "HIGH", "NETWORK", "SSL verification disabled.",
                _exts(".py")),
    LanguageRule("Python importlib user", r'importlib\.import_module\s*\(\s*(?:request|input)',
                "CRITICAL", "INJECTION", "Dynamic import with user input.",
                _exts(".py"), taint_source="request", taint_sink="importlib"),
    LanguageRule("Python glob user", r'glob\.glob\s*\(\s*(?:request|input)',
                "MEDIUM", "TRAVERSAL", "glob with user input.",
                _exts(".py"), taint_source="request", taint_sink="glob"),
    LanguageRule("Python getattr user", r'getattr\s*\(.*(?:request|input|args)',
                "HIGH", "INJECTION", "Dynamic attribute access with user input.",
                _exts(".py"), taint_source="request", taint_sink="getattr"),
    LanguageRule("Python django raw query",
                r'(?:objects\.raw|cursor\.execute)\s*\(\s*[f"\'].*\{.*\}',
                "CRITICAL", "INJECTION", "Django raw query with formatting.",
                _exts(".py"), taint_sink="raw"),
    LanguageRule("Python sqlalchemy text", r'text\s*\(\s*[f"\'].*\{.*\}',
                "HIGH", "INJECTION", "SQLAlchemy text() with formatting.",
                _exts(".py")),

    # ══════════════════════════════════════════════════════════════
    # PHP RULES
    # ══════════════════════════════════════════════════════════════
    LanguageRule("PHP eval", r'eval\s*\(', "CRITICAL", "INJECTION",
                "eval() executes arbitrary code.",
                _exts(".php"), taint_sink="eval"),
    LanguageRule("PHP system", r'system\s*\(', "CRITICAL", "INJECTION",
                "system() executes commands.",
                _exts(".php"), taint_source="$_GET", taint_sink="system"),
    LanguageRule("PHP exec", r'exec\s*\(', "CRITICAL", "INJECTION",
                "exec() executes commands.",
                _exts(".php"), taint_source="$_GET", taint_sink="exec"),
    LanguageRule("PHP passthru", r'passthru\s*\(', "CRITICAL", "INJECTION",
                "passthru() executes commands.",
                _exts(".php"), taint_source="$_GET", taint_sink="passthru"),
    LanguageRule("PHP shell_exec", r'shell_exec\s*\(', "CRITICAL", "INJECTION",
                "shell_exec() executes commands.",
                _exts(".php"), taint_source="$_GET", taint_sink="shell_exec"),
    LanguageRule("PHP popen", r'popen\s*\(', "HIGH", "INJECTION",
                "popen() executes commands.",
                _exts(".php"), taint_sink="popen"),
    LanguageRule("PHP proc_open", r'proc_open\s*\(', "HIGH", "INJECTION",
                "proc_open() executes commands.",
                _exts(".php"), taint_sink="proc_open"),
    LanguageRule("PHP unserialize", r'unserialize\s*\(', "CRITICAL", "DESERIALIZATION",
                "PHP unserialize allows object injection.",
                _exts(".php"), taint_sink="unserialize"),
    LanguageRule("PHP include variable",
                r'(?:include|require|include_once|require_once)\s*\(\s*\$',
                "CRITICAL", "TRAVERSAL", "Dynamic include - RFI/LFI.",
                _exts(".php"), taint_sink="include"),
    LanguageRule("PHP echo user input",
                r'(?:echo|print)\s+\$_(?:GET|POST|REQUEST|COOKIE|SERVER)',
                "CRITICAL", "XSS", "PHP output of user input without escaping.",
                _exts(".php"), taint_source="$_GET", taint_sink="echo"),
    LanguageRule("PHP extract user input", r'extract\s*\(\s*\$_',
                "HIGH", "INJECTION", "extract() with user input.",
                _exts(".php"), taint_source="$_GET", taint_sink="extract"),
    LanguageRule("PHP parse_str", r'parse_str\s*\(\s*(?:\$_|\$)',
                "HIGH", "INJECTION", "parse_str() variable overwrite.",
                _exts(".php"), taint_sink="parse_str"),
    LanguageRule("PHP preg_replace /e", r'preg_replace\s*\(.*/e',
                "CRITICAL", "INJECTION", "preg_replace /e - code execution.",
                _exts(".php")),
    LanguageRule("PHP create_function", r'create_function\s*\(',
                "CRITICAL", "INJECTION", "create_function() - code injection.",
                _exts(".php")),
    LanguageRule("PHP header injection", r'header\s*\(\s*["\'].*\$',
                "HIGH", "INJECTION", "header() with variable - injection.",
                _exts(".php"), taint_sink="header"),
    LanguageRule("PHP file_get_contents url",
                r'file_get_contents\s*\(\s*["\']https?://',
                "MEDIUM", "SSRF", "file_get_contents with URL.",
                _exts(".php"), taint_sink="file_get_contents"),
    LanguageRule("PHP file_put_contents", r'file_put_contents\s*\(.*\$',
                "HIGH", "TRAVERSAL", "file_put_contents with variable.",
                _exts(".php"), taint_sink="file_put_contents"),
    LanguageRule("PHP move_uploaded_file", r'move_uploaded_file\s*\(',
                "MEDIUM", "UPLOAD", "File upload - validate type.",
                _exts(".php")),
    LanguageRule("PHP SimpleXML", r'SimpleXMLElement\s*\(', "MEDIUM", "XSS",
                "PHP SimpleXML - disable external entities.",
                _exts(".php")),
    LanguageRule("PHP libxml entity", r'libxml_disable_entity_loader\s*\(\s*false',
                "HIGH", "XSS", "PHP entity loader enabled.",
                _exts(".php")),
    LanguageRule("PHP curl_setopt", r'curl_setopt\s*\(.*CURLOPT_URL',
                "MEDIUM", "SSRF", "Dynamic URL in cURL.",
                _exts(".php"), taint_sink="curl"),

    # ══════════════════════════════════════════════════════════════
    # JAVASCRIPT/NODE RULES
    # ══════════════════════════════════════════════════════════════
    LanguageRule("JS eval", r'(?<!\w)eval\s*\(', "HIGH", "INJECTION",
                "eval() executes arbitrary code.",
                _exts(".js", ".ts", ".jsx", ".tsx"), taint_sink="eval"),
    LanguageRule("JS new Function", r'new\s+Function\s*\(', "HIGH", "INJECTION",
                "Function constructor - code injection.",
                _exts(".js", ".ts", ".jsx", ".tsx")),
    LanguageRule("JS child_process", r'child_process\.(?:exec|spawn|execSync)\s*\(',
                "HIGH", "INJECTION", "Node.js child process.",
                _exts(".js", ".ts"), taint_sink="child_process"),
    LanguageRule("JS innerHTML", r'\.innerHTML\s*=', "HIGH", "XSS",
                "innerHTML enables XSS.",
                _exts(".js", ".ts", ".jsx", ".tsx", ".html", ".vue", ".svelte")),
    LanguageRule("JS document.write", r'document\.write\s*\(', "HIGH", "XSS",
                "document.write() enables XSS.",
                _exts(".js", ".ts", ".html")),
    LanguageRule("JS jQuery html", r'\$\([^)]+\)\.html\s*\(', "HIGH", "XSS",
                "jQuery .html() enables XSS.",
                _exts(".js", ".ts", ".html")),
    LanguageRule("JS dangerouslySetInnerHTML", r'dangerouslySetInnerHTML',
                "HIGH", "XSS", "React dangerouslySetInnerHTML.",
                _exts(".js", ".ts", ".jsx", ".tsx")),
    LanguageRule("JS v-html", r'v-html\s*=', "HIGH", "XSS",
                "Vue v-html renders raw HTML.",
                _exts(".vue", ".js", ".ts")),
    LanguageRule("JS setTimeout string", r'setTimeout\s*\(\s*["\']',
                "MEDIUM", "INJECTION", "setTimeout with string.",
                _exts(".js", ".ts")),
    LanguageRule("JS setInterval string", r'setInterval\s*\(\s*["\']',
                "MEDIUM", "INJECTION", "setInterval with string.",
                _exts(".js", ".ts")),
    LanguageRule("JS require user", r'require\s*\(\s*(?:req|input|param)',
                "HIGH", "INJECTION", "Dynamic require with user input.",
                _exts(".js", ".ts"), taint_source="req", taint_sink="require"),
    LanguageRule("JS crypto createCipher", r'crypto\.createCipher\s*\(',
                "HIGH", "CRYPTO", "createCipher is deprecated.",
                _exts(".js", ".ts")),
    LanguageRule("JS fetch user", r'fetch\s*\([^)]*\+',
                "MEDIUM", "SSRF", "Dynamic URL in fetch.",
                _exts(".js", ".ts"), taint_sink="fetch"),
    LanguageRule("JS axios user", r'axios\.(?:get|post|put)\s*\([^)]*\+',
                "MEDIUM", "SSRF", "Dynamic URL in axios.",
                _exts(".js", ".ts"), taint_sink="axios"),
    LanguageRule("JS insertAdjacentHTML", r'\.insertAdjacentHTML\s*\(',
                "HIGH", "XSS", "insertAdjacentHTML enables XSS.",
                _exts(".js", ".ts", ".html")),
    LanguageRule("JS outerHTML", r'\.outerHTML\s*=', "HIGH", "XSS",
                "outerHTML enables XSS.",
                _exts(".js", ".ts", ".html")),
    LanguageRule("JS ng-bind-html", r'ng-bind-html\s*=', "HIGH", "XSS",
                "Angular ng-bind-html.",
                _exts(".js", ".ts", ".html")),

    # ══════════════════════════════════════════════════════════════
    # JAVA RULES
    # ══════════════════════════════════════════════════════════════
    LanguageRule("Java Runtime.exec", r'Runtime\.getRuntime\(\)\.exec\s*\(',
                "CRITICAL", "INJECTION", "Runtime.exec() execution.",
                _exts(".java"), taint_sink="Runtime.exec"),
    LanguageRule("Java ProcessBuilder", r'new\s+ProcessBuilder\s*\(',
                "HIGH", "INJECTION", "ProcessBuilder - validate arguments.",
                _exts(".java")),
    LanguageRule("Java ObjectInputStream", r'ObjectInputStream.*readObject',
                "CRITICAL", "DESERIALIZATION", "Java deserialization - RCE.",
                _exts(".java"), taint_sink="readObject"),
    LanguageRule("Java Statement.execute",
                r'Statement\.execute\s*\(\s*["\'].*\+',
                "CRITICAL", "INJECTION", "SQL statement concatenation.",
                _exts(".java"), taint_sink="Statement.execute"),
    LanguageRule("Java JNDI injection",
                r'(?:InitialContext|lookup)\s*\(\s*(?:request|param)',
                "CRITICAL", "INJECTION", "JNDI lookup with user input.",
                _exts(".java"), taint_source="request", taint_sink="lookup"),
    LanguageRule("Java MD5", r'MessageDigest\.getInstance\s*\(\s*["\']MD5["\']',
                "HIGH", "CRYPTO", "MD5 is broken.",
                _exts(".java")),
    LanguageRule("Java SHA1", r'MessageDigest\.getInstance\s*\(\s*["\']SHA-?1["\']',
                "MEDIUM", "CRYPTO", "SHA1 is deprecated.",
                _exts(".java")),
    LanguageRule("Java TrustAll SSL", r'SSLContext.*init\s*\(.*null.*TrustAll',
                "HIGH", "NETWORK", "Trust-all SSL context.",
                _exts(".java")),
    LanguageRule("Java XPath injection", r'XPath.*evaluate\s*\(',
                "MEDIUM", "INJECTION", "XPath with user input.",
                _exts(".java"), taint_sink="XPath.evaluate"),
    LanguageRule("Java BeanUtils", r'BeanUtils\.populate\s*\(',
                "HIGH", "INJECTION", "BeanUtils mass assignment.",
                _exts(".java")),
    LanguageRule("Java LDAP search",
                r'(?:DirContext|LdapContext)\.search\s*\(',
                "HIGH", "INJECTION", "LDAP search - validate input.",
                _exts(".java"), taint_sink="LDAP.search"),

    # ══════════════════════════════════════════════════════════════
    # C#/.NET RULES
    # ══════════════════════════════════════════════════════════════
    LanguageRule("C# SqlCommand concat", r'SqlCommand\s*\(.*\+',
                "CRITICAL", "INJECTION", "SQL concatenation - injection.",
                _exts(".cs"), taint_sink="SqlCommand"),
    LanguageRule("C# BinaryFormatter",
                r'BinaryFormatter.*Deserialize',
                "CRITICAL", "DESERIALIZATION", ".NET BinaryFormatter RCE.",
                _exts(".cs"), taint_sink="BinaryFormatter.Deserialize"),
    LanguageRule("C# Response.Write user",
                r'Response\.Write\s*\(\s*(?:Request|Request\[)',
                "HIGH", "XSS", "XSS via Response.Write.",
                _exts(".cs"), taint_source="Request", taint_sink="Response.Write"),
    LanguageRule("C# MD5 Create", r'MD5\.Create\s*\(',
                "HIGH", "CRYPTO", "MD5 is broken.",
                _exts(".cs")),
    LanguageRule("C# Process.Start", r'Process\.Start\s*\(',
                "MEDIUM", "INJECTION", "Process.Start - validate args.",
                _exts(".cs")),
    LanguageRule("C# AllowAnyOrigin", r'AllowAnyOrigin\s*\(\)',
                "MEDIUM", "CONFIG", "CORS allows all origins.",
                _exts(".cs")),
    LanguageRule("C# Newtonsoft deserialize",
                r'JsonConvert\.DeserializeObject\s*\(.*Request',
                "HIGH", "DESERIALIZATION", "Deserializing user JSON.",
                _exts(".cs"), taint_source="Request", taint_sink="DeserializeObject"),

    # ══════════════════════════════════════════════════════════════
    # GO RULES
    # ══════════════════════════════════════════════════════════════
    LanguageRule("Go exec.Command", r'exec\.Command\s*\(',
                "HIGH", "INJECTION", "Go exec.Command execution.",
                _exts(".go"), taint_sink="exec.Command"),
    LanguageRule("Go sql.Query concat",
                r'(?:sql\.Query|db\.Query)\s*\(.*\+',
                "CRITICAL", "INJECTION", "SQL concatenation - injection.",
                _exts(".go"), taint_sink="sql.Query"),
    LanguageRule("Go template.HTML", r'template\.HTML\s*\(',
                "HIGH", "XSS", "template.HTML bypasses escaping.",
                _exts(".go")),
    LanguageRule("Go InsecureSkipVerify", r'InsecureSkipVerify\s*:\s*true',
                "HIGH", "NETWORK", "TLS verification disabled.",
                _exts(".go")),
    LanguageRule("Go md5.New", r'md5\.New\s*\(',
                "HIGH", "CRYPTO", "Go MD5 is broken.",
                _exts(".go")),
    LanguageRule("Go sha1.New", r'sha1\.New\s*\(',
                "MEDIUM", "CRYPTO", "Go SHA1 is deprecated.",
                _exts(".go")),
    LanguageRule("Go http.Get user",
                r'http\.(?:Get|Post|Do)\s*\(\s*(?:req|request)',
                "MEDIUM", "SSRF", "Go HTTP with user URL.",
                _exts(".go"), taint_source="req", taint_sink="http.Get"),

    # ══════════════════════════════════════════════════════════════
    # RUBY RULES
    # ══════════════════════════════════════════════════════════════
    LanguageRule("Ruby system", r'system\s*\(', "HIGH", "INJECTION",
                "Ruby system() - command injection.",
                _exts(".rb"), taint_sink="system"),
    LanguageRule("Ruby exec", r'exec\s*\(', "HIGH", "INJECTION",
                "Ruby exec() - command injection.",
                _exts(".rb"), taint_sink="exec"),
    LanguageRule("Ruby Marshal.load", r'Marshal\.load\s*\(',
                "CRITICAL", "DESERIALIZATION", "Marshal.load - RCE.",
                _exts(".rb"), taint_sink="Marshal.load"),
    LanguageRule("Ruby YAML.load", r'YAML\.load\s*\((?!.*safe)',
                "HIGH", "DESERIALIZATION", "YAML.load without safe_load.",
                _exts(".rb")),
    LanguageRule("Ruby render inline", r'render\s+inline:',
                "CRITICAL", "INJECTION", "ERB inline rendering - SSTI.",
                _exts(".rb"), taint_sink="render"),
    LanguageRule("Ruby send user", r'\.send\s*\(\s*(?:params|input)',
                "HIGH", "INJECTION", "Ruby send with user input.",
                _exts(".rb"), taint_source="params", taint_sink="send"),
    LanguageRule("Ruby eval", r'(?:eval|class_eval|module_eval)\s*\(',
                "HIGH", "INJECTION", "Ruby eval - code injection.",
                _exts(".rb"), taint_sink="eval"),

    # ══════════════════════════════════════════════════════════════
    # PERL RULES
    # ══════════════════════════════════════════════════════════════
    LanguageRule("Perl system", r'system\s*\(', "HIGH", "INJECTION",
                "Perl system() - command injection.",
                _exts(".pl", ".pm"), taint_sink="system"),
    LanguageRule("Perl exec", r'exec\s*\(', "HIGH", "INJECTION",
                "Perl exec() - command injection.",
                _exts(".pl", ".pm"), taint_sink="exec"),
    LanguageRule("Perl eval", r'eval\s*\(', "HIGH", "INJECTION",
                "Perl eval - code injection.",
                _exts(".pl", ".pm"), taint_sink="eval"),

    # ══════════════════════════════════════════════════════════════
    # LUA RULES
    # ══════════════════════════════════════════════════════════════
    LanguageRule("Lua loadstring", r'loadstring\s*\(', "HIGH", "INJECTION",
                "loadstring() - code injection.",
                _exts(".lua"), taint_sink="loadstring"),
    LanguageRule("Lua os.execute", r'os\.execute\s*\(', "HIGH", "INJECTION",
                "os.execute() - command injection.",
                _exts(".lua"), taint_sink="os.execute"),
    LanguageRule("Lua io.popen", r'io\.popen\s*\(', "HIGH", "INJECTION",
                "io.popen() - command injection.",
                _exts(".lua"), taint_sink="io.popen"),

    # ══════════════════════════════════════════════════════════════
    # SHARED CROSS-LANGUAGE RULES (weak crypto, insecure random, etc.)
    # ══════════════════════════════════════════════════════════════
    LanguageRule("ECB Mode", r'modes\.ECB|MODE_ECB',
                "HIGH", "CRYPTO", "ECB mode is insecure.",
                _exts(".py", ".java", ".cs", ".go", ".rb", ".php")),
    LanguageRule("Insecure Random (Python)", r'(?<!\w)random\.(?:random|randint|choice)\s*\(',
                "MEDIUM", "CRYPTO", "Non-cryptographic random.",
                _exts(".py")),
    LanguageRule("Insecure Random (JS)", r'Math\.random\s*\(',
                "MEDIUM", "CRYPTO", "Math.random() is not secure.",
                _exts(".js", ".ts", ".jsx", ".tsx")),
    LanguageRule("Insecure Random (Java)", r'new\s+Random\s*\(',
                "MEDIUM", "CRYPTO", "java.util.Random is not secure.",
                _exts(".java")),
    LanguageRule("Insecure Random (Go)", r'(?:rand\.Intn|rand\.Int|rand\.Float)',
                "MEDIUM", "CRYPTO", "Go math/rand is not secure.",
                _exts(".go")),

    # ── SSRF (shared) ──
    LanguageRule("SSRF (Python requests)", r'requests\.(?:get|post|put|delete)\s*\([^)]*\+',
                "HIGH", "SSRF", "Dynamic URL in requests.",
                _exts(".py"), taint_sink="requests"),
    LanguageRule("SSRF (Python urllib)", r'urllib\.request\.urlopen\s*\([^)]*\+',
                "HIGH", "SSRF", "Dynamic URL in urlopen.",
                _exts(".py"), taint_sink="urlopen"),
    LanguageRule("SSRF (Java URL)", r'new\s+URL\s*\(\s*(?:request|param)',
                "HIGH", "SSRF", "Java URL from user input.",
                _exts(".java"), taint_source="request", taint_sink="URL"),

    # ── XXE (shared) ──
    LanguageRule("XXE (Python xml)", r'(?:xml\.etree\.ElementTree|lxml\.etree)\.parse',
                "MEDIUM", "XSS", "XML parsing - XXE risk.",
                _exts(".py")),
    LanguageRule("XXE (DOMParser)", r'DOMParser\s*\(',
                "MEDIUM", "XSS", "XML parsing in browser.",
                _exts(".js", ".ts")),

    # ── SSTI (shared) ──
    LanguageRule("SSTI (Twig)", r'\$twig->render\s*\(',
                "HIGH", "INJECTION", "Twig template injection.",
                _exts(".php"), taint_sink="twig.render"),
    LanguageRule("SSTI (Freemarker)", r'Freemarker.*process\s*\(',
                "HIGH", "INJECTION", "Freemarker template injection.",
                _exts(".java"), taint_sink="Freemarker.process"),
    LanguageRule("SSTI (Thymeleaf)", r'Thymeleaf.*process\s*\(',
                "HIGH", "INJECTION", "Thymeleaf template injection.",
                _exts(".java"), taint_sink="Thymeleaf.process"),

    # ── Open Redirect ──
    LanguageRule("Open Redirect (PHP)", r'header\s*\(\s*["\']Location:\s*["\'].*\$',
                "HIGH", "REDIRECT", "PHP redirect with variable.",
                _exts(".php"), taint_sink="header"),
    LanguageRule("Open Redirect (JS)", r'window\.location\s*=.*(?:param|query|input)',
                "MEDIUM", "REDIRECT", "JS redirect with user input.",
                _exts(".js", ".ts")),

    # ── Session/Cookie ──
    LanguageRule("Insecure Cookie",
                r'(?:Set-Cookie|set_cookie|res\.cookie)\s*\(.*(?:secure\s*[=:]\s*false|HttpOnly\s*[=:]\s*false)',
                "MEDIUM", "SESSION", "Insecure cookie settings.",
                _exts(".php", ".js", ".ts", ".py", ".rb")),

    # ── Framework configuration (context-aware) ──
    LanguageRule("Django ALLOWED_HOSTS wildcard",
                r'ALLOWED_HOSTS\s*=\s*\[[^\]]*[\'"]\*[\'"][^\]]*\]',
                "HIGH", "CONFIG",
                "ALLOWED_HOSTS '*' permits host header spoofing.",
                _exts(".py")),
    LanguageRule("Django CSRF disabled globally",
                r'(?:CSRF_MIDDLEWARE|MIDDLEWARE\s*=.*csrf)',
                "LOW", "CONFIG", "Verify CSRF middleware is present.",
                _exts(".py")),
    LanguageRule("Spring actuator full exposure",
                r'management\.endpoints\.web\.exposure\.include\s*=\s*\*',
                "HIGH", "CONFIG",
                "All Spring actuator endpoints exposed - info/heapdump leak secrets.",
                _exts(".properties", ".yml", ".yaml")),

    # ── Kotlin / Swift / Scala (newly routed languages) ──
    LanguageRule("Kotlin Runtime.exec", r'Runtime\.getRuntime\(\)\.exec\s*\(',
                "CRITICAL", "INJECTION", "Runtime.exec() execution.",
                _exts(".kt"), taint_sink="Runtime.exec"),
    LanguageRule("Kotlin rawQuery", r'\.rawQuery\s*\(',
                "HIGH", "INJECTION", "Android rawQuery - use parameterized selection.",
                _exts(".kt"), taint_sink="rawQuery"),
    LanguageRule("Swift NSAllowArbitraryLoads",
                r'NSAllowsArbitraryLoads\s*=\s*(?:true|YES)',
                "MEDIUM", "NETWORK", "App Transport Security disabled.",
                _exts(".swift", ".plist")),
    LanguageRule("Scala Runtime.exec", r'Runtime\.getRuntime\(\)\.exec\s*\(',
                "CRITICAL", "INJECTION", "Runtime.exec() execution.",
                _exts(".scala"), taint_sink="Runtime.exec"),

    # ── C/C++ dangerous functions ──
    LanguageRule("C system()", r'\bsystem\s*\(', "HIGH", "INJECTION",
                 "system() executes shell commands - injection risk with untrusted input.",
                 _exts(".c", ".cpp", ".h", ".hpp"), taint_sink="system"),
    LanguageRule("C strcpy", r'\bstrcpy\s*\(', "HIGH", "INJECTION",
                 "strcpy() has no bounds checking - buffer overflow risk. Use strncpy.",
                 _exts(".c", ".cpp", ".h", ".hpp")),
    LanguageRule("C gets()", r'\bgets\s*\(', "CRITICAL", "INJECTION",
                 "gets() cannot be used safely - remove it.",
                 _exts(".c", ".cpp", ".h", ".hpp")),
]
